In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
a=np.zeros((3,3),dtype='int8')
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [5]:
np.ones((7,4),dtype='int16')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [7]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.full_like(a.shape,dtype='int16',fill_value='2')
a.shape

(3, 3)

In [20]:
output = np.zeros((7,7))
output
z = np.ones((5,5))
z[2,2]=5
output[1:-1,1:-1]=z
output

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [22]:
a=np.array([1,2,3,4,5])
b=a.copy()
b[2]=20
print(a)

[1 2 3 4 5]


In [25]:
c=np.array(([1,2,3,4,5],[6,7,8,9,10]))
d=np.max(c,axis=1).sum()

In [26]:
print(d)

15
