In [1]:
import sys
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
text = np.array([1,3,5])

In [4]:
text

array([1, 3, 5])

In [5]:
a = np.array([1,2,3,4])

In [6]:
b = np.array([0,0.5,1,1.5,2])

In [7]:
a[0],b[1]

(1, 0.5)

In [10]:
a[0:]

array([1, 2, 3, 4])

In [17]:
a[:2]

array([1, 2])

In [19]:
A = np.array([['a','b','c'],['d','e','f'],['g','h','i']])

In [20]:
A

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [21]:
print(A[:,:2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [23]:
A.shape

(3, 3)

In [24]:
A.ndim

2

In [29]:
A[0:2,:]

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [30]:
B=np.array([[1,3,5],[2,4,6],[3,6,9]])

In [31]:
B.sum()

39

In [32]:
B.sum(axis=0)

array([ 6, 13, 20])

In [33]:
B.sum(axis=1)

array([ 9, 12, 18])

In [34]:
B


array([[1, 3, 5],
       [2, 4, 6],
       [3, 6, 9]])

In [35]:
a = np.arange(5)

In [36]:
a

array([0, 1, 2, 3, 4])

In [37]:
a+20

array([20, 21, 22, 23, 24])

In [38]:
print(a<=3)

[ True  True  True  True False]


In [39]:
import pandas as pd

In [40]:
certificate_earned= pd.Series([8,2,5,2],index=['Tom','Kris','Ahmad','Beau'])

In [41]:
print(certificate_earned)

Tom      8
Kris     2
Ahmad    5
Beau     2
dtype: int64


In [42]:
g7_pop=pd.Series([35.467,63.951,80.980,60.665,127.061,64.571,318.523])

In [43]:
g7_pop

0     35.467
1     63.951
2     80.980
3     60.665
4    127.061
5     64.571
6    318.523
dtype: float64

In [44]:
g7_pop.name="Group of 7 Population"

In [45]:
g7_pop

0     35.467
1     63.951
2     80.980
3     60.665
4    127.061
5     64.571
6    318.523
Name: Group of 7 Population, dtype: float64

In [46]:
g7_pop.index=['Canada','France','Germany','Italy','Japan','United Kingdom','United States']

In [47]:
g7_pop

Canada             35.467
France             63.951
Germany            80.980
Italy              60.665
Japan             127.061
United Kingdom     64.571
United States     318.523
Name: Group of 7 Population, dtype: float64

In [49]:
g7_pop.values

array([ 35.467,  63.951,  80.98 ,  60.665, 127.061,  64.571, 318.523])

In [50]:
g7_pop['Italy']

60.665

In [52]:
g7_pop[g7_pop.values >=100]

Japan            127.061
United States    318.523
Name: Group of 7 Population, dtype: float64

In [56]:
not_italy = g7_pop[g7_pop.index != 'Italy']

In [57]:
not_italy

Canada             35.467
France             63.951
Germany            80.980
Japan             127.061
United Kingdom     64.571
United States     318.523
Name: Group of 7 Population, dtype: float64