In [4]:
import sys
import numpy as np
import pandas as pd

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
text = np.array([1,3,5])

In [4]:
text

array([1, 3, 5])

In [5]:
a = np.array([1,2,3,4])

In [6]:
b = np.array([0,0.5,1,1.5,2])

In [7]:
a[0],b[1]

(1, 0.5)

In [10]:
a[0:]

array([1, 2, 3, 4])

In [17]:
a[:2]

array([1, 2])

In [19]:
A = np.array([['a','b','c'],['d','e','f'],['g','h','i']])

In [20]:
A

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [21]:
print(A[:,:2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [23]:
A.shape

(3, 3)

In [24]:
A.ndim

2

In [29]:
A[0:2,:]

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [30]:
B=np.array([[1,3,5],[2,4,6],[3,6,9]])

In [31]:
B.sum()

39

In [32]:
B.sum(axis=0)

array([ 6, 13, 20])

In [33]:
B.sum(axis=1)

array([ 9, 12, 18])

In [34]:
B


array([[1, 3, 5],
       [2, 4, 6],
       [3, 6, 9]])

In [35]:
a = np.arange(5)

In [36]:
a

array([0, 1, 2, 3, 4])

In [37]:
a+20

array([20, 21, 22, 23, 24])

In [38]:
print(a<=3)

[ True  True  True  True False]


In [39]:
import pandas as pd

In [40]:
certificate_earned= pd.Series([8,2,5,2],index=['Tom','Kris','Ahmad','Beau'])

In [41]:
print(certificate_earned)

Tom      8
Kris     2
Ahmad    5
Beau     2
dtype: int64


In [42]:
g7_pop=pd.Series([35.467,63.951,80.980,60.665,127.061,64.571,318.523])

In [43]:
g7_pop

0     35.467
1     63.951
2     80.980
3     60.665
4    127.061
5     64.571
6    318.523
dtype: float64

In [44]:
g7_pop.name="Group of 7 Population"

In [45]:
g7_pop

0     35.467
1     63.951
2     80.980
3     60.665
4    127.061
5     64.571
6    318.523
Name: Group of 7 Population, dtype: float64

In [46]:
g7_pop.index=['Canada','France','Germany','Italy','Japan','United Kingdom','United States']

In [47]:
g7_pop

Canada             35.467
France             63.951
Germany            80.980
Italy              60.665
Japan             127.061
United Kingdom     64.571
United States     318.523
Name: Group of 7 Population, dtype: float64

In [49]:
g7_pop.values

array([ 35.467,  63.951,  80.98 ,  60.665, 127.061,  64.571, 318.523])

In [50]:
g7_pop['Italy']

60.665

In [52]:
g7_pop[g7_pop.values >=100]

Japan            127.061
United States    318.523
Name: Group of 7 Population, dtype: float64

In [56]:
not_italy = g7_pop[g7_pop.index != 'Italy']

In [57]:
not_italy

Canada             35.467
France             63.951
Germany            80.980
Japan             127.061
United Kingdom     64.571
United States     318.523
Name: Group of 7 Population, dtype: float64

In [8]:
certificates_earned = pd.DataFrame({'Certificates':[8,2,5,6],'Time (in months)':[16,5,9,12]},columns=['Certificates','Time (in months)'])

In [9]:
certificates_earned 

Certificates  Time (in months)
0             8                16
1             2                 5
2             5                 9
3             6                12

In [11]:
certificates_earned.index=['Tim','Kris','Ahmad','Beau']

In [12]:
certificates_earned

Certificates  Time (in months)
Tim               8                16
Kris              2                 5
Ahmad             5                 9
Beau              6                12

In [13]:
certificates_earned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Tim to Beau
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Certificates      4 non-null      int64
 1   Time (in months)  4 non-null      int64
dtypes: int64(2)
memory usage: 96.0+ bytes


In [14]:
certificates_earned.describe()

Certificates  Time (in months)
count          4.00          4.000000
mean           5.25         10.500000
std            2.50          4.654747
min            2.00          5.000000
25%            4.25          8.000000
50%            5.50         10.500000
75%            6.50         13.000000
max            8.00         16.000000

In [18]:
certificates_earned.loc['Kris']

Certificates        2
Time (in months)    5
Name: Kris, dtype: int64

In [19]:
certificates_earned.iloc[3]

Certificates         6
Time (in months)    12
Name: Beau, dtype: int64

In [20]:
certificates_earned['Certificates']

Tim      8
Kris     2
Ahmad    5
Beau     6
Name: Certificates, dtype: int64

In [21]:
certificates_earned.loc[['Kris','Tim']]

Certificates  Time (in months)
Kris             2                 5
Tim              8                16

In [26]:
certificates_earned.iloc[-1]

Certificates         6
Time (in months)    12
Name: Beau, dtype: int64

In [27]:
names =['Tim','Kris','Ahmad','Beau']

In [28]:
longest_streak=pd.Series([13,11,9,7],index=names)

In [29]:
certificates_earned['Longest_streak'] = longest_streak

In [30]:
certificates_earned

Certificates  Time (in months)  Longest_streak
Tim               8                16              13
Kris              2                 5              11
Ahmad             5                 9               9
Beau              6                12               7

In [31]:
certificates_earned[certificates_earned['Longest_streak']>=9]

Certificates  Time (in months)  Longest_streak
Tim               8                16              13
Kris              2                 5              11
Ahmad             5                 9               9